--DML (Data Manipulation Language) SELECT 
--DDL (Data Definition Language) CREATE, UPDATE, DELETE, INSERT ...
-- PIRVLEI GZA CREATE TABLEIS
CREATE TABLE MY_FIRST_TABLE (
CLIENT_ID NUMBER,
AMOUNT NUMBER,
TRANSACTION_DATE DATE,
TRANSACTION_TIMESTAMP TIMESTAMP,
TRANSACTION_DETAILS VARCHAR2(4000)
);
-- PIRVELI GZA INSERTIS
INSERT INTO MY_FIRST_TABLE (
CLIENT_ID, AMOUNT, TRANSACTION_DATE, TRANSACTION_TIMESTAMP, TRANSACTION_DETAILS)
VALUES 
(1, 100, SYSDATE, SYSDATE, 'RAGHACA TRANZAQCIA');
--MEORE GZA INSERTIS
INSERT INTO MY_FIRST_TABLE (
CLIENT_ID, AMOUNT, TRANSACTION_TIMESTAMP)
VALUES 
(2, 205, SYSDATE);
--MESAME GZA INSERTIS
INSERT INTO MY_FIRST_TABLE
VALUES 
(3, 203, SYSDATE, SYSDATE, 'RAGHACA');

COMMIT;

INSERT INTO MY_FIRST_TABLE
VALUES 
(4, 303, SYSDATE, SYSDATE, 'RAGHACA');

ROLLBACK;

DROP TABLE MY_FIRST_TABLE;

--2 GZA WASHLIS 
--1. UFRO SAFE, NELI
DELETE MY_FIRST_TABLE;
--2. SWRAFI UFRO
TRUNCATE TABLE MY_FIRST_TABLE;

-- DELETE
DELETE MY_FIRST_TABLE
WHERE CLIENT_ID = 1 AND AMOUNT = 100;
--IGIVE
DELETE FROM MY_FIRST_TABLE
WHERE CLIENT_ID = 1;

-----------------------------------------------------------
UPDATE MY_FIRST_TABLE 
SET AMOUNT = AMOUNT * 1.5 
WHERE CLIENT_ID = 1;

-- SUL BOLO POZICIA JOB_HISTORYDAN DAVUBRUNOT TANAMSHROMELS
MERGE INTO EMPLOYEES E 
  USING (
  SELECT * FROM (
  SELECT 
  EMPLOYEE_ID,
  JOB_ID,
  ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY END_DATE DESC) RNK
  FROM JOB_HISTORY
  ) WHERE RNK = 1
  ) B
ON (E.EMPLOYEE_ID = B.EMPLOYEE_ID)
WHEN MATCHED THEN UPDATE SET E.JOB_ID = B.JOB_ID;


CREATE TABLE MY_SECOND_TABLE AS 
SELECT E.*,D.DEPARTMENT_NAME,L.STREET_ADDRESS FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID;

SELECT * FROM ALL_TABLES WHERE OWNER = 'HR';
SELECT * FROM ALL_TAB_COLS WHERE OWNER = 'HR';


CREATE OR REPLACE VIEW MY_FIRST_VIEW AS 
SELECT E.*,D.DEPARTMENT_NAME,L.STREET_ADDRESS FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID;


CREATE TABLE MY_THIRD_TABLE (
CLIENT_ID NUMBER,
CONSTRAINT CLIENT_ID_PK PRIMARY KEY(CLIENT_ID));
--ARIS UNIKALURI
--AR SHEIDZLEBA IYOS NULL

CREATE TABLE OUR_DEPARTMENTS (
DEPARTMENT_ID NUMBER,
CONSTRAINT DEPARTMENT_ID_PK PRIMARY KEY(DEPARTMENT_ID)
);

CREATE TABLE OUR_EMPLOYEES (
EMPLOYEE_ID NUMBER,
DEPARTMENT_ID NUMBER,
CONSTRAINT DEPARTMENT_ID_FK FOREIGN KEY(DEPARTMENT_ID)
REFERENCES OUR_DEPARTMENTS(DEPARTMENT_ID)
);

CREATE TABLE MY_FIFTH_TABLE (
CLIENT_ID NUMBER NOT NULL,
PIRADI_NOMERI NUMBER UNIQUE,
TRANSACTION_DATE DATE DEFAULT SYSDATE,
GATAREBIS_TARIGHI DATE
);


--BINARY SEARCH
CREATE INDEX MY_FIRST_INDEX ON MY_FIFTH_TABLE(CLIENT_ID);

--YVELA INDEXIS CXRILI
SELECT * FROM ALL_IND_COLUMNS WHERE TABLE_NAME = 'MY_FIFTH_TABLE'


SELECT * FROM MY_FIFTH_TABLE WHERE CLIENT_ID = 100 AND PIRADI_NOMERI = '123123';

