CREATE OR REPLACE TRIGGER MY_THIRD_TRIGGER 
BEFORE INSERT ON HR.SOME_TABLE
BEGIN 
  UPDATE EMPLOYEES 
  SET SALARY = SALARY * 1.5;
END;

CREATE [OR REPLACE] TRIGGER MY_FIRST_TRIGGER 
{BEFORE | AFTER} 
{INSERT [OR] UPDATE [OR] DELETE}
[OF COL_NAME]
ON TABLE_NAME
DECLARE 
V_MY_FIRST_VAR NUMBER;
BEGIN
  
END;
/
