CREATE OR REPLACE FUNCTION EXTRACT_LAST_WORD(
P_SENTENCE IN VARCHAR2,
P_NUMBERS IN NUMBER DEFAULT 2
)
RETURN VARCHAR2 
IS 

V_LAST_WORD VARCHAR2(1000);

BEGIN 
SELECT
SUBSTR(P_SENTENCE, 
INSTR(P_SENTENCE,
' ',
1,
LENGTH(P_SENTENCE) - LENGTH(REPLACE(P_SENTENCE, ' ',''))) + 1)
INTO V_LAST_WORD
FROM DUAL;

RETURN V_LAST_WORD;

END EXTRACT_LAST_WORD;
/
