--2
-- WINA LEQCIA
SELECT EMPLOYEE_ID, FIRST_NAME AS SAXELI, LAST_NAME AS GVARI 
FROM EMPLOYEES EMP
WHERE EMPLOYEE_ID = 100
ORDER BY SAXELI, FIRST_NAME;

--WHERE 
SELECT * FROM EMPLOYEES EMP
WHERE 
(FIRST_NAME = 'Steven' AND SALARY > 5000) 
OR 
(MANAGER_ID = 100 AND HIRE_DATE < '15JUL2007')
OR 
(MANAGER_ID = 105);

-- S-IT IWYEBA STRINGI
SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE 'S%'

SELECT * FROM EMPLOYEES 
WHERE LAST_NAME LIKE '%s';

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE '%s%';

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE '___g';

SELECT * FROM EMPLOYEES 
WHERE LAST_NAME LIKE 'K___';
--GAERTIANEBA
SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE '%x____r';

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE '%x%' AND FIRST_NAME LIKE '%l%';

--SQL-IS IF IGIVE CASE WHEN SQL-SHI
SELECT 
CASE WHEN EMPLOYEE_ID = 100 THEN 1 ELSE 0 END,
EMPLOYEE_ID
FROM EMPLOYEES;

SELECT 
CASE WHEN EMPLOYEE_ID = 100 AND MANAGER_ID = 105 THEN 1
     WHEN MANAGER_ID = 100 THEN 2
     WHEN FIRST_NAME LIKE 'A%' THEN 3
ELSE 0
END
FROM EMPLOYEES;


SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100 OR EMPLOYEE_ID = 101 OR EMPLOYEE_ID = 102;

SELECT * FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN (100,101,102,103,104,105);

SELECT * FROM EMPLOYEES 
WHERE JOB_ID = 'AD_PRES' AND JOB_ID = 'AD_VP';

SELECT * FROM EMPLOYEES
WHERE 1=0;

--ABS (MODULI -50 -> 50)
SELECT ABS(100 - 150) FROM DUAL;
--CEIL  (CEILING) GAMOAQVS ZEVIT DAMRGVALEBULI RICXVI 50.5 - > 51, 50.001 -> 51
SELECT CEIL(100.003) FROM DUAL;
--FLOOR GAMOAQVS QVEVIT DAMRGVALEBULI RICXVI 50.999 -> 50
SELECT FLOOR(100.999999) FROM DUAL;
--ROUND, DAMRGVALEBA, PIRVELI PARAMETRI RASAC VAMRGVALEBT, MEORE PARAMETRI
--ROMEL ERTEULZE GVINDA DAMRGVALEBA.
SELECT ROUND(100.5456,2) FROM DUAL;
SELECT ROUND(135.3,-2) FROM DUAL;
--GREATEST, ABRUNEBS UDIDESS SVETEBS(AN MITITEBUL RICXVEBS SHORIS)
SELECT GREATEST(GREATEST(EMPLOYEE_ID, MANAGER_ID), DEPARTMENT_ID) FROM EMPLOYEES;
--LEAST, ABRUNEBS UMCIRESS SVETEBS(AN MITITEBUL RICXVEBS SHORIS)
SELECT LEAST(EMPLOYEE_ID, MANAGER_ID) FROM EMPLOYEES;
--MOD (NASHTIS FUNQCIA)
SELECT MOD(9, 2) FROM DUAL;
--SQRT (KVADRATULI FESVI)
SELECT SQRT(9) FROM DUAL;
--TRUNC (104.2123432 -> 104, PIRDAPIR ACHRIS MDZIMIS SHEMDEG RICXVEBS)
SELECT TRUNC(SALARY + 0.5) FROM EMPLOYEES;


-- STRING FUNCTIONS
--INITCAP (PIRVEL ASOEBS ADIDEBS WINADADEBASHI
SELECT INITCAP('nata gigi giorgi') FROM EMPLOYEES;
--LENGTH, ABRUNEBS STRINGIS SIGRDZES, AMASHI SHEDIS SPACEBI, #-EBI 
--*-EBI YVELAFERI RAC IKAVEBS ADGILS.
SELECT LENGTH(FIRST_NAME) FROM EMPLOYEES;
SELECT LENGTH('a *# ') from dual;
--LOWER, AKONVERTIREBS STRINGS QVEDA ASOEBSHI. MAGALITAD
--ME MIYVars sql -> me miyvars sql
SELECT LOWER('GREOIGWEFdsadas') from dual;


SELECT FIRST_NAME, LOWER(FIRST_NAME) FROM EMPLOYEES 
WHERE lower(first_name) ='Steven'; -- yoveltvis 0s daabrunebs

SELECT * FROM EMPLOYEES 
WHERE lower(first_name) ='steven';
--UPPER, AKONVERTIREBS STRINGS DID ASOEBSHI. MAGALITAD
--me miyvARS SQL -> ME MIYVARS SQL
SELECT * FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME) = 'STEVEN';

SELECT * FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME) LIKE '%WEQ';

SELECT * FROM EMPLOYEES 
WHERE (UPPER(FIRST_NAME) LIKE '%S%' OR 
       UPPER(FIRST_NAME) LIKE '%A%' OR 
       UPPER(EMAIL) LIKE '%H%') AND JOB_ID = 'AD_VP'
--INSTR, edzebs stringshi meore strings.
--pirveli parametri aris rashic modzebnos
--meore parametri aris ra modzebnos
--mesame parametri aris stringis meramdene poziciidan daiwyos dzebna
--meotxe parametri aris romeli shemtxveva daabrunos, anu tu vedzebt spaces
--da stringshi aris 5 space, tu chavwert 2-s daabrunebs meore spaces mdebareobas
SELECT INSTR(UPPER(FIRST_NAME),'E',1, 2), FIRST_NAME FROM EMPLOYEES 
--CONCAT, sql-shi stringebis gaertianeba(midgma, concatenacia):
SELECT FIRST_NAME ||' '|| LAST_NAME || ' ' || EMAIL FROM EMPLOYEES;
-- REPLACE, chanacvleba stringshi stringis stringit.
SELECT replace(UPPER(first_name),'E','#') FROM EMPLOYEES;
--SUBSTR, stringidan garkveuli poziciebit stringis amogheba.
--pirveli parametri stringi saidanac unda amovighot garkveuli stringi
--meore parametri romeli poziciidan daiwyos
--mesame parametri(optional) ramdeni aso amoighos meore parametris shemdeg
SELECT REPLACE('ganacxadi: 123123123', 'ganacxadi: ', '') FROM DUAL;

SELECT SUBSTR('giorgi', 2, 3) from DUAL

--RICXVEBI GAMOVITANOT AM STRINGIDAN
SELECT 
SUBSTR('ganasdfcxadi:  123123',
INSTR('ganasdfcxadi:  123123',' ', 1,
LENGTH('ganasdfcxadi:  123123') - LENGTH(REPLACE('ganasdfcxadi:  123123',' ',''))) + 1
)
FROM DUAL;

--MIZANI: MIVIGHOT RAMDENI SPACE ARIS STRINGSHI
--1. CHAVANACVLOT YVELA SPACE SICARIELIT
--2. DAVTVALOT ZOMA STRINGIS
--3. DAVTVALOT ARA CHANACVLEBULI STRINGIS ZOMA 
--4. GAMOVAKLOT ERTMANETS(AMIT VIGHEBT RAMDENI SPACE ARIS STRINGSHI)
--5. RAMDENI SPACE-C ARIS STRINGSHI VTQVAT 5, MEXUTE SPACE IQNEBA BOLO SPACE
--6. AMIS SHEMDEG VIPOVOT ME5 SPACES POZICIA, 
--7. SUBSTR-IT GAMOVITANOT ME-5 SPACES POZICIIDAN(+1) BOLOMDE

-- 1
SELECT REPLACE('ganasdfcxadi:  123123', '') FROM DUAL;
-- 2
SELECT LENGTH(REPLACE('ganasdfcxadi:  123123',' ', '')) FROM DUAL;
-- 3
SELECT LENGTH('ganasdfcxadi:  123123') FROM DUAL;
-- 4 (3-S VAKLEBT 2S) GVAQ 2 SPACE
SELECT LENGTH('ganasdfcxadi:  123123') - LENGTH(REPLACE('ganasdfcxadi:  123123',' ', '')) FROM DUAL;
-- 6
SELECT INSTR('ganasdfcxadi:  123123',' ', 1, LENGTH('ganasdfcxadi:  123123') - LENGTH(REPLACE('ganasdfcxadi:  123123',' ', ''))) FROM DUAL
--7 
SELECT SUBSTR('ganasdfcxadi:  123123', 
       INSTR('ganasdfcxadi:  123123',' ', 1, LENGTH('ganasdfcxadi:  123123') - LENGTH(REPLACE('ganasdfcxadi:  123123',' ', ''))) + 1) FROM DUAL




2. გამოიტანეთ ყველა თანამშრომლები, ცხრილი დაალაგეთ შემდეგი ლოგიკით:
პირველ რიგში წამოიღოს ისეთი თანამშრომლები რომლებიც 90-ე დეპარტამენტში არიან დასაქმებულები, 
შემდეგ ისეთი თანამშრომლები რომელთა ხელფასი > 2000-ზე 
და შემდეგ ისეთი თანამშრომლები რომელთა სახელი შეიცავს 4-ზე მეტ ასოს

select A.* from employees A
order by 
CASE WHEN DEPARTMENT_ID = 90 THEN 1 
     WHEN SALARY > 10000 THEN 2
     WHEN LENGTH(FIRST_NAME) > 4 THEN 3
     ELSE 4
END
