CREATE TABLE FIRST_IMPORT_FROM_EXCEL (
HIRE_DATE DATE,
FIRST_NAME VARCHAR2(1000)
);

SELECT * FROM FIRST_IMPORT_FROM_EXCEL

--ME-2 GZA
SELECT * FROM FIRST_IMPORT_FROM_EXCEL where 1=0 FOR UPDATE;

commit;

--me3 gza
select a.*,a.rowid from first_import_from_excel a;

commit;



select a.*,a.rowid from first_import_from_excel a;

commit;

----------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM FIRST_IMPORT_FROM_EXCEL;

ALTER TABLE FIRST_IMPORT_FROM_EXCEL ADD TRANSACTION_AMOUNT NUMBER;
ALTER TABLE FIRST_IMPORT_FROM_EXCEL DROP COLUMN TRANSACTION_AMOUNT;
ALTER TABLE FIRST_IMPORT_FROM_EXCEL MODIFY TRANSACTION_AMOUNT VARCHAR2(1000);
ALTER TABLE FIRST_IMPORT_FROM_EXCEL 
ADD CONSTRAINT PK_EXCEL_CONSTRAINT PRIMARY KEY(FIRST_NAME);

SELECT * FROM FIRST_IMPORT_FROM_EXCEL;

BEGIN
  SOME_PROCEDURE_1(
               P_EMPLOYEE_ID => 109
               );     
END;


BEGIN 
  PIRVELI_PROCEDURE(P_MIN_SALARY => 0, P_MAX_SALARY =>0);
END; 

SELECT HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID = 100

SELECT HIRE_DATE 
  --INTO V_EMPLOYEE_HIRE_DATE
  FROM EMPLOYEES 
  WHERE EMPLOYEE_ID IN (102, 100)
