SELECT * FROM SOME_TEMP_TABLE FOR UPDATE;

ALTER TABLE SOME_TEMP_TABLE ADD SOME_COLUMN NUMBER;
ALTER TABLE SOME_TEMP_TABLE DROP COLUMN SOME_COLUMN;
ALTER TABLE SOME_TEMP_TABLE ADD SOME_COLUMN NUMBER;
ALTER TABLE SOME_TEMP_TABLE MODIFY SOME_COLUMN VARCHAR2(100);
ALTER TABLE SOME_TEMP_TABLE ADD CONSTRAINT PK_TEMP_TABLE PRIMARY KEY (FIRST_NAME);


select * from some_temp_table

truncate table some_temp_table;

BEGIN 
  some_procedure('9NOV2022', 'IRAKLI');
END;

SELECT * FROM SOME_TEMP_TABLE 
WHERE FIRST_NAME = 'IRAKLI';


