SELECT * FROM EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;
SELECT 
FIRST_NAME, 
LAST_NAME, 
SALARY * 1.5, 
500 * 5 + 100/2 AS CALCULATION 
FROM EMPLOYEES;
--TEXT FUNCTIONS
--SUBSTR, INSTR, REPLACE, LENGTH
--SUBSTR STRINGIDAN STRINGIS AMOGHEBA POZICIEBIS MITITEBIT 
SELECT SUBSTR('RAGHAC WINADADEBA', 2, 3) FROM DUAL;
SELECT SUBSTR('RAGHAC WINADADEBA', 2) FROM DUAL;
--INSTR STRINGSHI STRINGIS POZICIIS POVNA
SELECT INSTR('RAGHAC WINADADEBA','C') FROM DUAL; -- 1 DA 1 BOLO 2 PARAMETRI
SELECT INSTR('RAGHAC WINADADEBA','C' ,1, 2) FROM DUAL; --ME-2 SHEMTXVEVA C-SI
SELECT INSTR('RAGHAC WINADADEBA','C' ,7, 1) FROM DUAL; --ME7DAN DAIWYOS DZEBNA
--REPLACE, STRINGIS CHANACVLEBA
SELECT REPLACE('RAGHAC WINADADEBA',' ','*') FROM DUAL;
--LENGTH, STRINGIS ZOMA
SELECT LENGTH('RAGHAC WINADADEBA') FROM DUAL;

--NUMERIC FUNCTIONS 
--ROUND, CEIL, FLOOR, ABS, NVL, SQRT, TRUNC, MOD 
--ROUND - DAMRGVALEBA
SELECT ROUND(15.67, 1) FROM DUAL;
SELECT ROUND(15.64, 1) FROM DUAL;
SELECT ROUND(15.64, -1) FROM DUAL;
SELECT ROUND(15.64, 0) FROM DUAL;
--CEIL - ZEMOT DAMRGVALEBA
SELECT CEIL(15.64) FROM DUAL;
--FLOOR - QVEMOT DAMRGVALEBA 
SELECT FLOOR(15.64) FROM DUAL;
--ABS - MODULI
SELECT ABS(-15) FROM DUAL;
SELECT ABS(15) FROM DUAL;
--NVL ARC NUMERIC ARIS DA ARC TEXTURI, NULL-S GADAGVIQCEVS MNISHVNELOBAD
SELECT NVL(COMMISSION_PCT, 0.5), COMMISSION_PCT FROM EMPLOYEES;
--SQRT - FESVI
SELECT SQRT(16) FROM DUAL;
--TRUNC 
SELECT TRUNC(16.5423423) FROM DUAL;
--MOD 
SELECT MOD(16, 3) FROM DUAL;

--DATE FUNCTIONS 
--ADD_MONTHS, SYSDATE, EXTRACT, LAST_DAY, MONTHS_BETWEEN, NEXT_DAY, TO_CHAR, TO_DATE, TRUNC.
--ADD_MONTHS- TVEEBIS DAMATEBA/GAMOKLEBA
SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, -1) FROM DUAL;
--SYSDATE - AXLANDELI DRO DA TARIGHI
SELECT SYSDATE FROM DUAL;
--EXTRACT - WLIS/TVIS/DGHIS... AMOGHEBA
SELECT EXTRACT (YEAR FROM SYSDATE) FROM DUAL;
SELECT EXTRACT (MONTH FROM SYSDATE) FROM DUAL;
SELECT EXTRACT (DAY FROM SYSDATE) FROM DUAL;
-- LAST_DAY - TVIS BOLO TARIGHI
SELECT LAST_DAY(SYSDATE) FROM DUAL;
-- MONTHS_BETWEEN - TVEEBS SHORIS GANSXVAVEBA
SELECT MONTHS_BETWEEN(SYSDATE, SYSDATE - 75) FROM DUAL;
-- NEXT DAY, SHEMDEGI "PARASKEVI" MAGALITAD
SELECT NEXT_DAY(SYSDATE, 'FRIDAY') FROM DUAL;
-- TO_CHAR, TARIGHIS STRINGSHI GADAYVANA
SELECT TO_CHAR(SYSDATE, 'YYYY/MM') FROM DUAL;
-- TO_DATE, STRINGIS TARIGHSHI GADAYVANA
SELECT TO_DATE('15/05/2022','DD/MM/YYYY') FROM DUAL;
SELECT TO_DATE('2022/11' || '/01', 'YYYY/MM/DD') FROM DUAL;
-- TRUNC - TARIGHEBZE DATOVEBS MARTO DGHE/TVE/WELI
SELECT TRUNC(SYSDATE) FROM DUAL;

--TARIGHEBZE!!!! 
SELECT SYSDATE FROM DUAL
WHERE SYSDATE >= '1NOV2022' AND SYSDATE < '1DEC2022';

--CASE WHENIS SHEMTXVEVEBI
SELECT 
CASE WHEN SALARY > 5000 THEN 1
     WHEN SALARY > 3000 THEN 2
     WHEN SALARY > 2000 THEN 3 
ELSE 2 
END 
FROM EMPLOYEES;

SELECT 
CASE WHEN SALARY > 5000 AND JOB_ID = 'AD_VP' THEN 1
     WHEN SALARY > 3000 AND FIRST_NAME LIKE 'S%' THEN 2
     WHEN SALARY > 2000 THEN 3 
ELSE 2 
END 
FROM EMPLOYEES;
--------
--WHERE 
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID * 5 > 100;

--CASE SENSITIVITY!
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%e%';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S%';

SELECT * FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME) LIKE '__S%';

--WHERE BEVRI CONDITIONIT 
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE >= '1JAN2003'
AND FIRST_NAME LIKE '%e%' AND COMMISSION_PCT IS NULL 
AND MANAGER_ID = 105;
--OR-S VWERT FRTXILAD VIYOT 
SELECT * FROM EMPLOYEES 
WHERE (HIRE_DATE >= '1JAN2003' OR EMPLOYEE_ID = 112) AND
FIRST_NAME LIKE '%e%' AND COMMISSION_PCT IS NULL 
AND MANAGER_ID = 105;


--AGREGACIEBIS FUNQCIEBI 
--SUM,COUNT,AVG, MAX, MIN
--JAMI
SELECT SUM(SALARY) FROM EMPLOYEES;
SELECT COUNT(1) FROM EMPLOYEES; 
SELECT AVG(SALARY) FROM EMPLOYEES;
SELECT MAX(SALARY), MIN(SALARY) FROM EMPLOYEES;

SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) AS SUM_SALARY, MAX(SALARY), MIN(SALARY) 
FROM EMPLOYEES
WHERE HIRE_DATE >= '1JAN2003' AND JOB_ID LIKE '%AD%'
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING SUM(SALARY) >= 4500 AND MAX(SALARY) >= 23000;

--SUBQUERY
SELECT * FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS
                        WHERE DEPARTMENT_NAME = 'Marketing');

--JOIN(INNER)
SELECT E.*,D.DEPARTMENT_NAME, L.STREET_ADDRESS FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L 
ON D.LOCATION_ID = L.LOCATION_ID
--LEFT JOIN
SELECT * FROM EMPLOYEES E 
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
--RIGHT JOIN
--FULL JOIN
--1LI BAZA - KLIENTEBI ROMLEBMAC TANXA GADARICXES
--ME2 BAZA - KLIENTEBI ROMLEBSAC TANXA CHAURICXES
--CLIENT_ID  GADARICXVA  CHARICXVA
   1           100         50 
   2           50          null
   3           NULL        40
   4           200         150

--GADARICXVA DA CHARICXVA
WITH XAXVI AS (
SELECT * FROM GADARICXVEBI
LEFT JOIN CHARICXVEBI
ON ---
),
XAXVI_2 AS (
SELECT * FROM CHARICXVEBI
LEFT JOIN GADARICXVEBI
ON ---
)
SELECT * FROM XAXVI
UNION
SELECT * FROM XAXVI_2

--UNION, UNION ALL
SELECT 1, 'RAGHACA' FROM DUAL
UNION ALL
SELECT 1, 'RAGHACA' FROM DUAL

-----------------------------------------------
--WINDOW FUNQCIEBI
--ROW_NUMBER() 
--RANK
--DENSE_RANK
--LAG
--LEAD
--AGGREGATE FUNQCIEBI WINDOW FUNQCIEBTAN ERTAD
SELECT E.*,ROW_NUMBER() OVER (ORDER BY SALARY DESC) FROM EMPLOYEES E;
SELECT E.*,RANK() OVER (ORDER BY SALARY DESC) FROM EMPLOYEES E;
SELECT E.*,DENSE_RANK() OVER (ORDER BY SALARY DESC) FROM EMPLOYEES E;
SELECT E.*, DENSE_RANK() OVER (PARTITION BY DEPARTMENT_ID,JOB_ID ORDER BY SALARY) FROM EMPLOYEES E;
SELECT E.*, LAG(EMPLOYEE_ID, 1) OVER (ORDER BY EMPLOYEE_ID) FROM EMPLOYEES E;
SELECT E.*, LEAD(EMPLOYEE_ID, 1) OVER (ORDER BY EMPLOYEE_ID) FROM EMPLOYEES E;
SELECT EMPLOYEE_ID, HIRE_DATE,DEPARTMENT_ID, SALARY, SUM(SALARY) OVER (PARTITION BY DEPARTMENT_ID) 
FROM EMPLOYEES;
SELECT EMPLOYEE_ID, HIRE_DATE,DEPARTMENT_ID, SALARY, 
SUM(SALARY) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY) 
FROM EMPLOYEES;


-----------------------------------------------------------------------------------------------------






